const GET_DINNER_NAV = "DINNER_NAV_BAR";
const GET_DINNER_RES = "GET_DINNER_RES";
const ADD_DINNER_RES = "ADD_DINNER_RES";
const HASMORE = "HASMORE";
const SCROLL_BACK_TOP = "SCROLL_BACK_TOP"
export {GET_DINNER_NAV,GET_DINNER_RES,ADD_DINNER_RES,HASMORE,SCROLL_BACK_TOP}