const CHANGE_ACTIVE_ITEM = "CHANGE_ACTIVE_ITEM"
const ADD_HOME_SPECIALS = "ADD_HOME_SPECIALS"
const HASMORE = "HASMORE"
const GET_LIST_INFO = "GET_LIST_INFO"
const GET_HOME_DETAIL = "GET_HOME_DETAIL"
const GET_BANNER_DETAIL = "GET_BANNER_DETAIL"
export { CHANGE_ACTIVE_ITEM, ADD_HOME_SPECIALS, HASMORE, GET_LIST_INFO, GET_HOME_DETAIL, GET_BANNER_DETAIL}