const GET_NAV_INFO = "GET_NAV_INFO"
const GET_HOME_DETAIL = "GET_HOME_DETAIL"
const GET_SALE_DETAIL = "GET_SALE_DETAIL"
const BTN_BANNER = "BTN_BANNER"
const RESTAURANTS = "RESTAURANTS"
const BACK_TOP = "BACK_TOP"


export {
    GET_NAV_INFO,
    GET_HOME_DETAIL,
    GET_SALE_DETAIL,
    BTN_BANNER, 
    RESTAURANTS, 
    BACK_TOP
    
}
